name       : perl-html-tree
version    : 5.07
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/K/KE/KENTNL/HTML-Tree-5.07.tar.gz : f0374db84731c204b86c1d5b90975fef0d30a86bd9def919343e554e31a9dbbf
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Make parse trees out of HTML source
description: |
    Make parse trees out of HTML source
builddeps  :
    - perl
    - perl-module-build
    - perl-test-fatal
    - perl-html-parser
    - perl-html-tagset
rundeps :
    - perl-html-parser
    - perl-html-tagset
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
