name       : ttf-quintessential
version    : 1.001
release    : 2
source     :
    - https://github.com/google/fonts/raw/8d2bb82bece80d7475c3e5d63915f26e0e2f7c31/ofl/quintessential/Quintessential-Regular.ttf : 73d192f10dbfc716214aae282afb93036f12415d16adc9d6d0e981f34d829d32
license    : GPL-2.0-or-later # CHECK ME
summary    : Calligraphic typeface from Google by Brian J. Bonislawsky
description: |
    Calligraphic typeface from Google by Brian J. Bonislawsky
extract    : no
install    : |
    install -dm755 "${installdir}/usr/share/fonts/TTF/"
    install -Dpm644 $sources/*.ttf "${installdir}/usr/share/fonts/TTF/"
