name       : perl-bytes-random-secure
version    : 0.29
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAVIDO/Bytes-Random-Secure-0.29.tar.gz : 53bbd339e6a11efca07c619a615c7c188a68bb2be849a1cb7efc3dd4d9ae85ae
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Bytes::Random::Secure - Perl extension to generate cryptographically-secure random bytes.
description: |
    Bytes::Random::Secure - Perl extension to generate cryptographically-secure random bytes.
builddeps  :
    - perl
    - perl-math-random-isaac
    - perl-crypt-random-seed
rundeps    :
    - perl-math-random-isaac
    - perl-crypt-random-seed
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
