name       : virtualbox-tkg
version    : 6.1.22
release    : 3
source     :
    - https://download.virtualbox.org/virtualbox/6.1.22/VirtualBox-6.1.22.tar.bz2 : 99816d2a15205d49362a31e8ffeb8262d2fa0678c751dfd0a7c43b2faca8be49
license    : GPL-2.0-only
homepage   : https://www.virtualbox.org
summary    :
    - VirtualBox host modules for the linux-tkg kernel
description: |
    VirtualBox is a free powerful open source solution for running other x86 and x86_64 operating systems virtually on your computer.

    Installation Guide: https://getsol.us/articles/software/virtualbox/en/
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(SDL_ttf)
    - pkgconfig(alsa)
    - pkgconfig(devmapper)
    - pkgconfig(glu)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libelf)
    - pkgconfig(libIDL-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libxslt)
    - pkgconfig(opus)
    - pkgconfig(python3)
    - pkgconfig(vpx)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xmu)
    - pkgconfig(xorg-server)
    - pkgconfig(xrandr)
    - acpica-unix
    - cdrtools
    - docbook-xml
    - git
    - glibc-32bit-devel
    - libgcc-32bit
    - linux-tkg
    - linux-tkg-headers
permanent  :
    - /lib/modules
autodep    : no
rundeps    :
    - linux-tkg
    - virtualbox-common
setup      : |
    # Apply patches before we go off changing the tree
    %apply_patches

    # Ensure we don't ever use bundled libraries
    rm -rf src/libs/{libpng-*,libxml2-*,libxslt-*,zlib-*,boost-*}

    cp $pkgfiles/LocalConfig.kmk .
    echo "VBOX_GCC_OPT=$CXXFLAGS" >> LocalConfig.kmk

    ./configure --disable-kmods \
                --disable-docs \
                --disable-java \
                --with-makeself=/bin/true   # we don't need this guy; it's used by linux installer
build      : |
    source ./env.sh

    # The following is taken from
    # https://build.opensuse.org/package/view_file/openSUSE:Factory/virtualbox/virtualbox.spec?expand=1
    # in order to only build the kernel modules
    COMMON_KMK_FLAGS="
        KBUILD_VERBOSE=2 \
        KBUILD_TARGET=linux \
        BUILD_TARGET=linux \
        KBUILD_TARGET_ARCH=amd64 \
        BUILD_TARGET_ARCH=amd64"

    # Build additions to export the source code of vbox{guest,sf,video} to
    # out/linux.*/release/bin/additions/src/
    kmk ${COMMON_KMK_FLAGS} \
        VBOX_WITH_X11_ADDITIONS= \
        VBOX_ONLY_ADDITIONS=1
    # The following kmk commands are used to extract the source of
    # vbox{drv,netflt,netadp} without building the whole virtualbox
    # program.

    # 1. build src/bldprogs/ to get bin2c and VBoxTpG
    kmk -C src/bldprogs/ \
        ${COMMON_KMK_FLAGS} \
        VBOX_ONLY_EXTPACKS=1

    # 2. build src/VBox/HostDrivers/ with VBOX_ONLY_EXTPACKS=1 to
    #    get SUPR3.a for src/VBox/Runtime/
    kmk -C src/VBox/HostDrivers/ \
        ${COMMON_KMK_FLAGS} \
        VBOX_ONLY_EXTPACKS=1

    # 3. build src/VBox/Runtime/ with VBOX_ONLY_BUILD=1 to get
    #    VBoxRt.so for src/VBox/HostDrivers/Support/
    kmk -C src/VBox/Runtime/ \
        ${COMMON_KMK_FLAGS} \
        VBOX_ONLY_BUILD=1

    # 4. build src/VBox/HostDrivers/ to export the source of
    #    host kernel modules to out/linux.*/release/bin/src/
    kmk -C src/VBox/HostDrivers/ \
        ${COMMON_KMK_FLAGS}
    
    KERNEL_VERSION="$(echo "$(basename `readlink /usr/lib/kernel/default-tkg` | cut -d '.' -f 4,5,6)".tkg)"
    ##### hosts modules #####
    cd out/linux.amd64/release/bin
    for kern in "$KERNEL_VERSION"; do
        cp -a src ${kern}
        pushd ${kern}
            %make KERN_VER=${kern}
        popd
    done
install    : |
    ##### Host #####
    cd out/linux.amd64/release/bin
    
    KERNEL_VERSION="$(echo "$(basename `readlink /usr/lib/kernel/default-tkg` | cut -d '.' -f 4,5,6)".tkg)"
    # kernel modules
    for kern in "$KERNEL_VERSION"; do
        pushd ${kern}
            install -d -m 00755 $installdir/lib/modules/${kern}/extra
            install -m 00644 *.ko $installdir/lib/modules/${kern}/extra
        popd
    done
