name       : ttf-merriweather-sans
version    : 2.001
release    : 1
source     :
    - git|https://github.com/SorkinType/Merriweather-Sans.git : a43147c5693999732cc74c53d186d861c29d3f73
license    : GPL-2.0-or-later # CHECK ME
summary    : A sans-serif typeface that is pleasant to read on screens by Sorkin Type Co
description: |
    A sans-serif typeface that is pleasant to read on screens by Sorkin Type Co
install    : |
    install -dm 755 "${installdir}/usr/share/fonts/TTF"
    install -m644 -Dt $installdir/usr/share/fonts/TTF/ fonts/ttf/*.ttf
