name       : perl-path-class
version    : 0.37
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/K/KW/KWILLIAMS/Path-Class-0.37.tar.gz : 654781948602386f2cb2e4473a739f17dc6953d92aabc2498a4ca2561bc248ce
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Cross-platform path specification manipulation
description: |
    OpenSSL glue that provides LWP https support
builddeps  :
    - perl
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
