name       : perl-date-manip
version    : 6.79
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/S/SB/SBECK/Date-Manip-6.79.tar.gz : 71a8c42ce4edbd46a3ca2a17a7218ceed958cd7ad0dfeb79389f23d0f466943a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Date::Manip - date manipulation routines
description: |
    Date::Manip - date manipulation routines
builddeps  :
    - perl
    # Tests
    - perl-test-inter
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
