name       : kshutdown
version    : 5.2
release    : 3
source     :
    - https://downloads.sourceforge.net/kshutdown/KShutdown/5.2/kshutdown-source-5.2.zip : 1ae0911b734a0d7eb12469ca95f066fb4d52c7880c2e9f1b692b236fd08337df
license    : GPL-3.0-or-later
summary    : Shutdown Utility
description: |
    Shutdown Utility
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kxmlgui-devel

rundebs    :
    - knotifyconfig
    - kidletime
    - hicolor-icon-theme
setup      : |
    %cmake 
build      : |
    %make
install    : |
    %make_install
