name       : thinkpad-scripts
version    : 4.12.0
release    : 3
source     :
    - git|https://github.com/martin-ueding/thinkpad-scripts.git : v4.12.0
license    : GPL-2.0-or-later # CHECK ME
summary    : Scripts for ThinkPad X220 & X230 Tablet rotation, docking, etc.
description: |
    Scripts for ThinkPad X220 & X230 Tablet rotation, docking, etc.
builddeps  :
    - pkgconfig(python3)
    - python-sphinx
rundeps    :
    - acpid2
    - alsa-utils
    - glib2
    - network-manager
    - pulseaudio
    - python-setuptools
    - systemd
    - usbutils
    - xbacklight
    - xinput
    - xorg-driver-input-wacom
    - xrandr
setup      : |
    %patch -p1 < $pkgfiles/activation_patch.patch
build      : |
    %make
install    : |
    %make_install
    %python3_install

    mkdir -p $installdir/%libdir%/udev
    mv $installdir/lib/* $installdir/%libdir%
    rmdir $installdir/lib

    mv $installdir/etc/* $installdir/usr/share/
    rmdir $installdir/etc
