name       : gcab
version    : 1.4
release    : 4
source     :
    - https://download.gnome.org/sources/gcab/1.4/gcab-1.4.tar.xz : 67a5fa9be6c923fbc9197de6332f36f69a33dadc9016a2b207859246711c048f
license    : LGPL-2.1-or-later
component  : system.utils
summary    : GLib Cabinet API
description: |
    GLib Cabinet API
builddeps  :
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
