name       : watchexec
version    : 1.10.3
release    : 1
source     :
    - https://github.com/watchexec/watchexec/archive/1.10.3.tar.gz : 2bbef078d3937764cfb063c6520eae5117eddb5cfd15efabc39a69fc69b9989e
license    : Apache
summary    : Executes commands in response to file modifications
description: |
    Executes commands in response to file modifications
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build %JOBS% --release --locked
install    : |
    install -Dm755 "target/release/watchexec" "$installdir/usr/bin/watchexec"

