name       : font-merriweather-sans-ttf
version    : 2.001
release    : 3
source     :
    - git|https://github.com/SorkinType/Merriweather-Sans.git : a43147c5693999732cc74c53d186d861c29d3f73
license    : OFL-1.1
summary    : A sans-serif typeface
description: |
    A sans-serif typeface that is pleasant to read on screens by Sorkin Type Co.
install    : |
    # Install fonts
    install -dm 755 "$installdir"/usr/share/fonts/truetype/merriweather-sans
    install -m644 -Dt "$installdir"/usr/share/fonts/truetype/merriweather-sans fonts/ttf/*.ttf
