name       : ttf-merriweather
version    : 2.005
release    : 1
source     :
    - git|https://github.com/SorkinType/Merriweather.git : c293ef9c184566dc19f74d15468fb6c03dd1042e
license    : GPL-2.0-or-later # CHECK ME
summary    : A typeface that is pleasant to read on screens by Sorkin Type Co
description: |
    A typeface that is pleasant to read on screens by Sorkin Type Co
install    : |
    install -dm 755 "${installdir}/usr/share/fonts/TTF"
    install -m644 -Dt $installdir/usr/share/fonts/TTF/ fonts/ttfs/*.ttf
