name       : linux-tkg
version    : 5.11.22
release    : 10
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.11.22.tar.xz : 11027c6114eb916edbcc37897226fb6263b2931911d2d5093550473ce1a57600
license    : GPL-2.0-only
component  :
    - kernel.image
    - headers : kernel.devel
summary    :
    - Linux kernel image and modules (tkg)
    - headers : Linux kernel headers (tkg)
description:
    - The Linux kernel and modules, the core of the operating system
    - headers : Headers required for building out of tree kernel modules
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libelf)
    - bc
    - btrfs-progs
    - cpio
    - dracut
    - intel-microcode
    - kbd
    - linux-firmware
    - lz4
    - perl
    - prelink
patterns   :
    - headers : /usr/src
permanent  :
    - /lib/modules
    - /usr/lib/kernel
    - /usr/src
replaces   :
    - kernel
    - kernel-modules
    - headers : kernel-headers
setup      : |
    %apply_patches
    # Set the version
    extraVersion="-${release}.tkg"
    sed -e "s/EXTRAVERSION =.*/EXTRAVERSION = $extraVersion/" -i Makefile

    # TKG - used commit: 29d86ed
    #
    # Graysky's cpu opts - https://github.com/graysky2/kernel_gcc_patch
    %patch -p1 < $pkgfiles/tkg/more-uarches-for-gcc-v10-and-kernel-5.8+.patch
    # Clear linux & TKG base patch
    %patch -p1 < $pkgfiles/tkg/0002-clear-patches.patch
    %patch -p1 < $pkgfiles/tkg/0003-glitched-base.patch

    # Undead PDS scheduler
    %patch -p1 < $pkgfiles/tkg/0005-v5.11_undead-pds099o.patch
    %patch -p1 < $pkgfiles/tkg/0005-undead-glitched-ondemand-pds.patch

    # Config settings from TKG which are not present in Solus already
    echo "# CONFIG_DYNAMIC_FAULT is not set" >> $pkgfiles/config
    sed -i -e 's/CONFIG_DEFAULT_FQ_CODEL=y/# CONFIG_DEFAULT_FQ_CODEL is not set/' $pkgfiles/config
    echo "CONFIG_DEFAULT_CAKE=y" >> $pkgfiles/config
    echo "# CONFIG_NTP_PPS is not set" >> $pkgfiles/config
    sed -i -e 's/CONFIG_ZSWAP_COMPRESSOR_DEFAULT_LZO=y/# CONFIG_ZSWAP_COMPRESSOR_DEFAULT_LZO is not set/' $pkgfiles/config
    sed -i -e 's/# CONFIG_ZSWAP_COMPRESSOR_DEFAULT_LZ4 is not set/CONFIG_ZSWAP_COMPRESSOR_DEFAULT_LZ4=y/' $pkgfiles/config
    sed -i -e 's/CONFIG_ZSWAP_COMPRESSOR_DEFAULT="lzo"/CONFIG_ZSWAP_COMPRESSOR_DEFAULT="lz4"/' $pkgfiles/config
    echo "# CONFIG_X86_P6_NOP is not set" >> $pkgfiles/config
    echo "# CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND is not set" >> $pkgfiles/config
    echo "# CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE is not set" >> $pkgfiles/config

    # OpenRGB
    echo "CONFIG_I2C_NCT6775=m" >> $pkgfiles/config

    # Inject CPU optimization options
    echo "# CONFIG_MK8SSE3 is not set" >> $pkgfiles/config
    echo "# CONFIG_MK10 is not set" >> $pkgfiles/config
    echo "# CONFIG_MBARCELONA is not set" >> $pkgfiles/config
    echo "# CONFIG_MBOBCAT is not set" >> $pkgfiles/config
    echo "# CONFIG_MJAGUAR is not set" >> $pkgfiles/config
    echo "# CONFIG_MBULLDOZER is not set" >> $pkgfiles/config
    echo "# CONFIG_MPILEDRIVER is not set" >> $pkgfiles/config
    echo "# CONFIG_MSTEAMROLLER is not set" >> $pkgfiles/config
    echo "# CONFIG_MEXCAVATOR is not set" >> $pkgfiles/config
    echo "# CONFIG_MZEN is not set" >> $pkgfiles/config
    echo "# CONFIG_MZEN2 is not set" >> $pkgfiles/config
    echo "# CONFIG_MATOM is not set" >> $pkgfiles/config
    echo "# CONFIG_MNEHALEM is not set" >> $pkgfiles/config
    echo "# CONFIG_MWESTMERE is not set" >> $pkgfiles/config
    echo "# CONFIG_MSILVERMONT is not set" >> $pkgfiles/config
    echo "# CONFIG_MSANDYBRIDGE is not set" >> $pkgfiles/config
    echo "# CONFIG_MIVYBRIDGE is not set" >> $pkgfiles/config
    echo "# CONFIG_MHASWELL is not set" >> $pkgfiles/config
    echo "# CONFIG_MBROADWELL is not set" >> $pkgfiles/config
    echo "# CONFIG_MSKYLAKE is not set" >> $pkgfiles/config
    echo "# CONFIG_MSKYLAKEX is not set" >> $pkgfiles/config
    echo "# CONFIG_MCANNONLAKE is not set" >> $pkgfiles/config
    echo "# CONFIG_MICELAKE is not set" >> $pkgfiles/config
    echo "# CONFIG_MGOLDMONT is not set" >> $pkgfiles/config
    echo "# CONFIG_MGOLDMONTPLUS is not set" >> $pkgfiles/config
    echo "# CONFIG_MCASCADELAKE is not set" >> $pkgfiles/config
    echo "# CONFIG_MCOOPERLAKE is not set" >> $pkgfiles/config
    echo "# CONFIG_MTIGERLAKE is not set" >> $pkgfiles/config

    # https://bbs.archlinux.org/viewtopic.php?pid=1863567#p1863567
    # Makes systemd-detect-virt --container to work correctly
    sed -i -e 's/CONFIG_SCHED_DEBUG=y/# CONFIG_SCHED_DEBUG is not set/' $pkgfiles/config
    sed -i -e 's/CONFIG_LATENCYTOP=y/# CONFIG_LATENCYTOP is not set/' $pkgfiles/config

    # PDS default config
    echo "CONFIG_SCHED_PDS=y" >> $pkgfiles/config

    # Disable CFS
    sed -i -e 's/CONFIG_FAIR_GROUP_SCHED=y/# CONFIG_FAIR_GROUP_SCHED is not set/' $pkgfiles/config
    sed -i -e 's/CONFIG_CFS_BANDWIDTH=y/# CONFIG_CFS_BANDWIDTH is not set/' $pkgfiles/config

    sed -i -e 's/int sched_yield_type __read_mostly = 1;/int sched_yield_type __read_mostly = 0;/' kernel/sched/pds.c

    # Zenify
    echo "CONFIG_ZENIFY=y" >> $pkgfiles/config

    # Compiler optimization level
    echo "# CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3 is not set" >> $pkgfiles/config

    # CPU optimizations
    sed -i -e 's/CONFIG_GENERIC_CPU=y/# CONFIG_GENERIC_CPU is not set/' $pkgfiles/config
    echo "CONFIG_MNATIVE=y" >> $pkgfiles/config

    # IRQ threading
    echo "# CONFIG_FORCE_IRQ_THREADING is not set" >> $pkgfiles/config

    # SMT Nice support
    echo "CONFIG_SMT_NICE=y" >> $pkgfiles/config

    # RQ sharing
    echo -e "# CONFIG_RQ_NONE is not set\n# CONFIG_RQ_SMT is not set\n# CONFIG_RQ_MC is not set\nCONFIG_RQ_MC_LLC=y\n# CONFIG_RQ_SMP is not set\n# CONFIG_RQ_ALL is not set" >> $pkgfiles/config

    # fsync
    %patch -p1 < $pkgfiles/tkg/0007-v5.11-fsync.patch

    # misc additions
    %patch -p1 < $pkgfiles/tkg/0012-misc-additions.patch

    # Patches for WRITE_WATCH support in Wine
    %patch -p1 < $pkgfiles/tkg/0001-mm-Support-soft-dirty-flag-reset-for-VA-range.patch
    %patch -p1 < $pkgfiles/tkg/0002-mm-Support-soft-dirty-flag-read-with-reset.patch

    # Ensure config is valid
    install $pkgfiles/config .config
    %make ARCH=x86_64 oldconfig
build      : |
    %make ARCH=x86_64 CONFIG_DEBUG_SECTION_MISMATCH=y
    %make -C tools/objtool
install    : |
    # Install kernel blob
    kernID="com.solus-project.tkg"
    kversion="${version}-${release}.tkg"
    install -D -m 0755 arch/x86/boot/bzImage $installdir/usr/lib/kernel/$kernID.${version}-${release}

    # Install additional files
    install -m 00644 .config $installdir/usr/lib/kernel/config-$kversion
    install -m 00644 System.map $installdir/usr/lib/kernel/System.map-$kversion
    install -m 00644 $pkgfiles/cmdline $installdir/usr/lib/kernel/cmdline-$kversion

    # Install kernel modules, disable depmod + firmware install
    install -D -d -m 00755 $installdir/lib/modules/$kversion
    %make ARCH=x86_64 INSTALL_MOD_PATH=$installdir/ modules_install KERNELRELEASE=$kversion mod-fw= DEPMOD=/bin/true

    # Remove broken links
    rm -v $installdir/lib/modules/${kversion}/{source,build}

    # Mark this as the default "tkg" kernel
    ln -sv $kernID.${version}-${release} $installdir/usr/lib/kernel/default-tkg

    # Fix mods
    depmod -b $installdir/ $kversion -a

    # Store vendor initrd within the kernel package, prevent mangling from fakeroot
    # 2021-01-20: Force early KMS for everything except Nouveau (this will not work with Nvidia propretary)
    LD_PRELOAD='' dracut --strip --tmpdir /tmp -N -f  \
        --kmoddir $installdir/lib/modules/${kversion} \
        --kver $kversion --add "bash systemd lvm dm rescue" \
        --prelink --strip --hardlink \
        --nomdadmconf --early-microcode \
        --add-drivers "amdgpu i915 qxl radeon virtio-gpu" \
        $installdir/usr/lib/kernel/initrd-$kernID.${version}-${release}

    # Install the headers
    tgtDir="/usr/src/linux-headers-$kversion"
    dstDir="$installdir/$tgtDir"
    install -D -d -m 00755 $dstDir
    find . -path './include/*' -prune -o -path './scripts/*' -prune -o -path './Documentation/*' -prune -o -type f \( -name 'Makefile*' -o -name 'Kconfig*' -o -name 'Kbuild*' -o -name '*.sh' -o -name '*.pl' -o -name '*.lds' \) -print | cpio -pVd --preserve-modification-time $dstDir/

    # Necessary for out of tree modules
    for h in "drivers/media/dvb-frontends" "drivers/media/tuners" "drivers/media/platform"; do
        install -D -d -m 00755 $dstDir/$h
        cp -a $h/*.h $dstDir/$h
    done

    # For a full headers pkg
    for p in "include" "scripts" "Documentation"; do
        cp -a $p $dstDir
    done

    # Nuke any unneeded bits.
    rm -f $dstDir/scripts/*.o
    rm -f $dstDir/scripts/*/*.o
    rm -rf $dstDir/Documentation/DocBook

    # Copy remaining include dirs
    (find arch -name include -type d -print | xargs -n1 -i: find : -type f) | cpio -pd --preserve-modification-time "$dstDir"

    # Shove last bits needed for out of tree kernel builds
    install -m 00644 Module.symvers $dstDir/.
    install -m 00644 System.map $dstDir/.
    install -m 00644 .config $dstDir/.config

    # Add objtool binary for CONFIG_STACK_VALIDATION (T5607)
    install -m 00755 tools/objtool/objtool $dstDir/tools/objtool/objtool

    # Fix up build/source links
    ln -sv build $installdir/lib/modules/$kversion/source
    ln -sv $tgtDir $installdir/lib/modules/$kversion/build
