name       : ttf-iosevka-aile
version    : 7.0.3
release    : 2
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v7.0.3/ttf-iosevka-aile-7.0.3.zip : e290be123db443561a97bdfcb4480f2ea2b8f2202178a9de1ad12a4021fb28bb
license    : GPL-2.0-or-later # CHECK ME
summary    : Quasi-proportional, sans-serif font.
description: |
    Quasi-proportional, sans-serif font.

install    : |
    install -d ${installdir}/usr/share/fonts/TTF/
    install -m644 $workdir/*.ttf ${installdir}/usr/share/fonts/TTF/
