name       : pydbus
version    : 0.6.0
release    : 1
source     :
    - https://github.com/LEW21/pydbus/archive/refs/tags/v0.6.0.tar.gz : dacdf0498a831c8b43a4f3d985d64f99f3093a8aaf4e2ea99981c30fdf1a42da
license    : LGPL-2.1-or-later
summary    : Pythonic DBus library
description: |
    Pythonic DBus library.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
