name       : pandoc-bin
version    : 2.14.0.1
release    : 7
source     :
    - https://github.com/jgm/pandoc/releases/download/2.14.0.1/pandoc-2.14.0.1-linux-amd64.tar.gz : 5c4c9a039e9eec53bca4c75ab4ae02091d8ab24cb25f3838334fa7fce1f1b8dd
    - https://github.com/jgm/pandoc/archive/refs/tags/2.14.0.1.tar.gz : 5f0a06f75151bcb179626e8b450ad64bc411edf3d89500b0ba5d3e3f8f7b8105
license    : BSD-3-Clause
component  : office
summary    : Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
description: |
    Pandoc is a Haskell library for converting from one markup format to another, and a command-line tool that uses this library
networking : yes
install    : |
    # First install completions
    install -dm 755 "$installdir/usr/share/bash-completion/completions"
    ./bin/pandoc --bash-completion >"$installdir/usr/share/bash-completion/completions/pandoc"

    # To avoid having to download over a gigabyte of haskell makedepends (400-ish for ghc, plus 750 in libs), we
    # just yoink the binary from static compiled binary distributed by pandoc:
    mkdir -p "$installdir/usr/share/pandoc"
    cp -R bin share "$installdir/usr"

    # We're still missing all the datafiles and so on. We get those from the source tarball...
    tar xvf $sources/$version.tar.gz  --strip 1
    cp -R data "$installdir/usr/share/pandoc/"
    cp COPYRIGHT MANUAL.txt "$installdir/usr/share/pandoc/"
