name       : pandoc-bin
version    : 2.16.2
release    : 8
source     :
    - https://github.com/jgm/pandoc/releases/download/2.16.2/pandoc-2.16.2-linux-amd64.tar.gz : f053aa621130383c9166db3a3a09fa5de95090e165711011607f84b285609bd1
    - https://github.com/jgm/pandoc/archive/refs/tags/2.16.2.tar.gz : 00816e746d7c8a0747b18b171ffbec5c02a8357b00d12daad13c5c4cf0efed63
license    : GPL-2.0-or-later
component  : office
summary    : Pandoc is a Haskell library for converting from one markup format to another
description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
install    : |
    # First install completions
    install -dm 755 "$installdir/usr/share/bash-completion/completions"
    ./bin/pandoc --bash-completion >"$installdir/usr/share/bash-completion/completions/pandoc"

    # To avoid having to download over a gigabyte of haskell makedepends
    # (400-ish for ghc, plus 750 in libs), we just yoink the binary from static
    # compiled binary distributed by pandoc:
    mkdir -p "$installdir/usr/share/pandoc"
    cp -R bin share "$installdir/usr"

    # We're still missing all the datafiles and so on. We get those from the
    # source tarball...
    tar xvf $sources/$version.tar.gz  --strip 1
    cp -R data "$installdir/usr/share/pandoc/"
    cp COPYRIGHT MANUAL.txt "$installdir/usr/share/pandoc/"
