name       : font-carlito-ttf
version    : 20130920
release    : 4
source     :
    - https://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz : 4bd12b6cbc321c1cf16da76e2c585c925ce956a08067ae6f6c64eff6ccfdaf5a
license    : OFL-1.1
summary    : Google's Carlito font
description: |
    Google's Carlito font
install    : |
    # Install fonts
    install -Dt "$installdir"/usr/share/fonts/truetype/carlito -m644 *.ttf

    # Install fontconfig
    install -Dt "$installdir"/usr/share/fontconfig/conf.avail -m644 "$pkgfiles"/*.conf
    install -dm00755 "$installdir"/usr/share/fonts/conf.d
    ln -sv /usr/share/fontconfig/conf.avail/62-google-crosextra-carlito.conf "$installdir"/usr/share/fonts/conf.d
