name       : xbindkeys
version    : 1.8.7
release    : 1
source     :
    - https://www.nongnu.org/xbindkeys/xbindkeys-1.8.7.tar.gz : a29b86a8ec91d4abc83b420e547da27470847d0efe808aa6e75147aa0adb82f2
license    : GPL-2.0-or-later # CHECK ME
summary    : Launch shell commands with your keyboard or your mouse under X
description: |
    Launch shell commands with your keyboard or your mouse under X
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(guile-2.0)
    - pkgconfig(tk)
    - pkgconfig(x11)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
