name       : pandoc-crossref-bin
version    : 0.3.12.1a
release    : 9
source     :
    - https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.12.1a/pandoc-crossref-Linux.tar.xz : 7500e31db12e634fe56bd8b6c9fa44ff16052a09212f0cfbe73b9e6b13a40e39
license    : BSD-3-Clause
component  : office
summary    : Pandoc filter for cross-references
description: |
    Pandoc filter for cross-references
rundeps    :
    - pandoc-bin
install    : |
    # To avoid having to download over a gigabyte of haskell makedepends
    # (400-ish for ghc, plus 750 in libs), we just yoink the binary from static
    # compiled binary distributed by pandoc:
    mkdir -p "$installdir/usr/bin"
    cp pandoc-crossref "$installdir/usr/bin/"
    mkdir -p "$installdir/usr/share/man/man1/"
    cp pandoc-crossref.1 "$installdir/usr/share/man/man1/"
