name       : perl-finance-quote
version    : 1.49
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/E/EC/ECOCODE/Finance-Quote-1.49.tar.gz : 95dbc4443ba656320b363c56625d04f379c943e202f60f40a2a35152b54bbf53
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Finance::Quote - Fetch stock prices over the Internet
description: |
    Finance::Quote - Fetch stock prices over the Internet
builddeps  :
    - perl
    # Tests:
    - libwww-perl
    - perl-json
    - perl-html-tableextract
    - perl-cgi
    - perl-html-tree
    - perl-html-tagset
    - perl-text-template
    - perl-datetime-format-strptime
    - perl-class-singleton
    - perl-package-deprecationmanager
    - perl-sub-install
    - perl-json-parse
    - perl-string-util
rundeps    :
    # Tests:
    - libwww-perl
    - perl-json
    - perl-html-tableextract
    - perl-cgi
    - perl-html-tree
    - perl-html-tagset
    - perl-text-template
    - perl-datetime-format-strptime
    - perl-class-singleton
    - perl-package-deprecationmanager
    - perl-sub-install
    - perl-json-parse
    - perl-string-util
    # Normal:
    - perl-crypt-ssleay
    - perl-date-calc
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
