name       : perl-json-parse
version    : 0.55
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/B/BK/BKB/JSON-Parse-0.55.tar.gz : dc9856dbc355114bcb0dc036bb632976b19b88d3a7ad59726f1fa917e7f5d256
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : JSON::Parse - Read JSON into a Perl variable
description: |
    JSON::Parse - Read JSON into a Perl variable
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
