name       : gsfonts
version    : 20180524
release    : 1
source     :
    - git|https://github.com/ArtifexSoftware/urw-base35-fonts.git : b758567463df532414c520cf008e27d9448b55a4
license    : GPL-2.0-or-later # CHECK ME
summary    : (URW)++ Core Font Set [Level 2]
description: |
    (URW)++ Core Font Set [Level 2]
install    : |
    install -Dt "${installdir}/usr/share/fonts/${pkgname}" -m644 fonts/*.otf
    install -Dt "${installdir}/usr/share/metainfo" -m644 appstream/*.xml

    install -d "${installdir}"/etc/fonts/conf.{avail,d}
    for _f in fontconfig/*.conf; do
        _fn="${installdir}/etc/fonts/conf.avail/69-${_f##*/}"
        install -m644 ${_f} "${_fn}"
        ln -srt "${installdir}/etc/fonts/conf.d" "${_fn}"
    done
