name       : plasma-wallpapers-dynamic
version    : 3.3.9
release    : 6
source     :
    - git|https://github.com/zzag/plasma5-wallpapers-dynamic.git : eb87fa359cc4134cb761a458b4d881f262b9a9cb
license    : GPL-2.0-or-later
summary    : Dynamic wallpaper plugin for KDE Plasma
description: |
    A wallpaper plugin for KDE Plasma that continuously updates the desktop
    background based on the current time in your location.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Location)
    - pkgconfig(libexif)
    - pkgconfig(libheif)
    - pkgconfig(Qt5QuickControls2)
    - kcmutils-devel
    - ki18n-devel
    - kirigami2-devel
    - kpackage-devel
    - extra-cmake-modules
    - plasma-framework-devel
rundeps    :
    - geoclue
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
