name       : libjcat
version    : 0.1.3
release    : 1
source     :
    - https://github.com/hughsie/libjcat/archive/0.1.3.tar.gz : 70336f56ab0b39274d59ae945528a0ba9c0cd120d664892097f6edc1de098fa6
license    : GPL-2.0-or-later # CHECK ME
summary    : Library for reading and writing Jcat files
description: |
    Library for reading and writing Jcat files
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gpgme)
    - pkgconfig(gobject-introspection-1.0)
    - vala
    - libgnutls-utils
    - help2man
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
