name       : direnv-2
version    : 2.28.0
release    : 2
source     :
    - https://github.com/direnv/direnv/archive/v2.28.0.tar.gz : fa539c63034b6161d8238299bb516dcec79e8905cd43ff2b9559ad6bf047cc93
license    : MIT
summary    : A shell extension that manages your environment
description: |
    A shell extension that manages your environment
networking : yes
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
