name       : arc-kde-theme
version    : 2019_rc1
release    : 2
source     :
    - git|https://github.com/PapirusDevelopmentTeam/arc-kde.git : e832daee0d97e27042cccd06b689bf6f73e5a7e9
license    : GPL-3.0-only
component  : desktop.theme
summary    : Arc KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Arc for Plasma 5 desktop with a few additions and
    extras.
install    : |
    %make_install
