name       : perl-test-inter
version    : 1.09
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/S/SB/SBECK/Test-Inter-1.09.tar.gz : 1e9f129cc1a001fb95449d385253b38afabf5b466e3b3bd33e4e430f216e177a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Framework for more readable interactive test scripts
description: |
    Framework for more readable interactive test scripts
builddeps  :
    - perl
    - perl-test-pod
    - perl-test-pod-coverage
    - perl-file-find-rule
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
check      : |
    %perl_build test
