name       : antigen
version    : 2.2.3.1
release    : 3
source     :
    - git|https://github.com/zsh-users/antigen.git : 64de2dcd95d6a8e879cd2244c763d99f0144e78e
license    : GPL-2.0-or-later # CHECK ME
summary    : A plugin manager for zsh, inspired by oh-my-zsh and vundle.
description: |
    A plugin manager for zsh, inspired by oh-my-zsh and vundle.
build      : |
    %make PREFIX=$installdir/usr/share/zsh
install    : |
    %make_install PREFIX=$installdir/usr/share/zsh
