name       : font-caladea-ttf
version    : 20200113
release    : 2
source     :
    - git|https://github.com/huertatipografica/Caladea.git : bea9e4996451fb18e0bdb5cbd177c8a263c0343d
license    : Apache-2.0
summary    : A serif font family metric-compatible with Cambria font family
description: |
    A serif font family metric-compatible with Cambria font family
install    : |
    install -Dt "$installdir/usr/share/fonts/caladea" -m644 fonts/ttf/*.ttf

    install -Dt "$installdir/etc/fonts/conf.avail" -m644 $pkgfiles/*.conf

    mkdir -p "$installdir/etc/fonts/conf.d"
    ln -srt "$installdir/etc/fonts/conf.d" "$installdir"/etc/fonts/conf.avail/62-caladea.conf
