name       : font-caladea-ttf
version    : 20200113
release    : 4
source     :
    - git|https://github.com/huertatipografica/Caladea.git : bea9e4996451fb18e0bdb5cbd177c8a263c0343d
license    : Apache-2.0
summary    : A serif font family metric-compatible with Cambria font family
description: |
    A serif font family metric-compatible with Cambria font family
install    : |
    # Install fonts
    install -Dt "$installdir/usr/share/fonts/truetype/caladea" -m644 fonts/ttf/*.ttf

    # Install fontconfig
    install -Dt "$installdir/usr/share/fontconfig/conf.avail" -m644 "$pkgfiles"/*.conf
    install -dm00755 "$installdir/usr/share/fonts/conf.d"
    ln -sv /usr/share/fontconfig/conf.avail/62-caladea.conf "$installdir/usr/share/fonts/conf.d"
