name       : perl-html-element-extended
version    : 1.18
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/M/MS/MSISK/HTML-Element-Extended-1.18.tar.gz : f3ef1af108f27fef15ebec66479f251ce08aa49bd00b0462c9c80c86b4b6b32b
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl extension for HTML::Element
description: |
    Perl extension for HTML::Element
builddeps  :
    - perl
    - perl-html-tree
rundeps    :
    - perl-html-tree
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
