name       : mp3wrap
version    : 0.5
release    : 1
source     :
    - http://prdownloads.sourceforge.net/mp3wrap/mp3wrap-0.5-src.tar.gz : 1b4644f6b7099dcab88b08521d59d6f730fa211b5faf1f88bd03bf61fedc04e7
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : Wrap MP3 Files into One Single Large Playable MP3
description: |
    Mp3Wrap is a free independent alternative to AlbumWrap. It's a command-line utility that wraps
    quickly two or more mp3 files in one single large playable mp3, without losing filenames and ID3
    informations (and without need of decoding/encoding). Also with the possibility of including
    other non mp3 files, such as PlayLists, info files, cover images, inside the mp3. This means
    that you obtain a large mp3 that you can split in any moment just using mp3splt and in few
    seconds you have all original files again! It's useful because files created with Mp3Wrap are
    easy to download. Infact who downloads has not to know each single song name and easy to play
    and even if you don't have mp3splt to split file, you can listen to it anyway.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
