name       : distrobox
version    : 1.2.9
release    : 1
source     :
    - https://github.com/89luca89/distrobox/archive/refs/tags/1.2.9.tar.gz : 643c3e91a8e687d2887b4d3ab7d061165eb1f690434abbde4150840e37b2b194
license    : GPL-3.0-or-later
summary    : Use any linux distribution inside your terminal.
description: |
    Use any Linux distribution inside your terminal. Distrobox uses podman or
    docker to create containers using the Linux distribution of your choice. The
    created container will be tightly integrated with the host, allowing sharing
    of the HOME directory of the user, external storage, external USB devices
    and graphical apps (X11/Wayland), and audio.
rundeps  :
    - podman
install    : |
    for file in distrobox*; do
        install -vDm755 -t "$installdir/usr/bin" $file
    done
