name       : perl-math-random-isaac
version    : 1.004
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/J/JA/JAWNSY/Math-Random-ISAAC-1.004.tar.gz : 2773f02fbf207e9745e76a037df08bf5a8cc987ed23c57040ce7f7b1561f2b7c
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Math::Random::ISAAC - Perl interface to the ISAAC PRNG algorithm
description: |
    Math::Random::ISAAC - Perl interface to the ISAAC PRNG algorithm
builddeps  :
    - perl
    - perl-test-nowarnings
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
