name       : materia-kde-theme
version    : '20210410'
release    : 10
source     :
    - https://github.com/PapirusDevelopmentTeam/materia-kde/archive/refs/tags/20210410.tar.gz : 35d5de39234a0fa70cdcd186e8a4524dca468e61fd58d1324db6de517d2864ff
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Materia KDE customization
rundeps    :
    - kvantum
description: |
    This is a port of the popular GTK theme Materia for Plasma 5 desktop with a few additions and extras.
install    : |
    %make_install
