name       : font-courier-prime-ttf
version    : 1.203
release    : 2
source     : 
    - https://quoteunquoteapps.com/courierprime/downloads/courier-prime.zip : d5d4faf1bee0d1f52bab1103cbfdfb354976331c86f999c110c22a098cb12d73
    - https://quoteunquoteapps.com/courierprime/downloads/courier-prime-sans.zip : 754b3937340f5522ccf96be7832efbd809ef93f373d51b12919adbd9c0a468d7
    - https://quoteunquoteapps.com/courierprime/downloads/courier-prime-code.zip : c400b6addeddef7c26a9943f847a8584c83d8bb775cd35da2dcd41c6ad98d827
    - https://quoteunquoteapps.com/courierprime/downloads/courier-prime-medium-semi-bold.zip : b1ec844f4fcdff58cf532e942ec74766bcf38e9c75fc06e1a99a24afedd41ecb
license    : OFL-1.1
summary    : Monospace Courier font alternative. It’s Courier, just better
description: |
    Monospace Courier font alternative. It’s Courier, just better
setup      : |
    unzip $sources/courier-prime-sans.zip
    unzip $sources/courier-prime-code.zip
    unzip $sources/courier-prime-medium-semi-bold.zip

install    : |
    # Install fonts
    install -d "$installdir/usr/share/fonts/TTF"
    # Courier Prime fonts expand to directory `Courier Prime`
    # Courier Prime Sans fonts expand to directory `CourierPrimeSans-master/ttf`
    # Courier Prime Code fonts expand to directory `ttf`
    # Courier Prime Medium & Semi-Bold fonts expand to base directory
    install -m644 {Courier\ Prime/,CourierPrimeSans-master/ttf/,ttf/,}*.ttf "$installdir/usr/share/fonts/TTF"
