name       : fonts-gsfonts
version    : 20180524
release    : 3
source     :
    - git|https://github.com/ArtifexSoftware/urw-base35-fonts.git : b758567463df532414c520cf008e27d9448b55a4
license    : AGPL-3.0
summary    : (URW)++ Core Font Set
description: |
    (URW)++ Core Font Set [Level 2].
install    : |
    # Install fonts
    install -Dt "$installdir"/usr/share/fonts/opentype/gsfonts -m644 fonts/*.otf
    install -Dt "$installdir/usr/share/metainfo" -m644 appstream/*.xml

    # Install fontconfig
    install -dm00755 "$installdir"/usr/share/fontconfig/conf.avail
    install -dm00755 "$installdir"/usr/share/fonts/conf.d
    for _f in fontconfig/*.conf; do
        _fn="$installdir/usr/share/fontconfig/conf.avail/69-${_f##*/}"
        install -m644 ${_f} "${_fn}"
        ln -svrt "$installdir/usr/share/fonts/conf.d" "${_fn}"
    done
