name       : perl-text-template
version    : 1.58
release    : 1
source     :
    - https://search.cpan.org/CPAN/authors/id/M/MS/MSCHOUT/Text-Template-1.58.tar.gz : 0c465757782c4bfb9b17335307a8286771fd36ea04d259bc454ac63355f2a287
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Expand template text with embedded perl
description: |
    Expand template text with embedded perl
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
