name       : vivaldi-widevine
version    : 4.10.1610.0
release    : 5
source     :
    - https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_80.0.3987.100-1_amd64.deb : f9aede3a3cb27ef96fc42bf6bde7b6215a974cc82c024133451e1f0ca745ea50
license    : GPL-2.0-or-later # CHECK ME
summary    : A browser plugin designed for the viewing of premium video content, standalone for vivaldi
description: |
    A browser plugin designed for the viewing of premium video content, standalone for vivaldi
strip      : no
setup      : |
    bsdtar -x --strip-components 4 -f data.tar.xz opt/google/chrome/WidevineCdm
install    : |
    install -dm755 "$installdir/opt/google/chrome/"
    cp -a WidevineCdm "$installdir/opt/google/chrome/"
